export const styles = {
  container: {
    minHeight: '100vh',
    background: '#f3f4f6',
    fontFamily: "'Segoe UI', sans-serif",
  },
  header: {
    background: 'linear-gradient(135deg, #1e3a5f 0%, #dc2626 100%)',
    color: 'white',
    padding: '16px 24px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
  },
  headerContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  logo: { fontSize: '40px' },
  title: { fontSize: '22px', fontWeight: 'bold', margin: 0 },
  subtitle: { fontSize: '13px', opacity: 0.85, margin: 0 },
  main: {
    display: 'flex',
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '24px',
    gap: '24px',
  },
  nav: {
    width: '200px',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  navBtn: {
    width: '100%',
    padding: '10px 14px',
    background: 'white',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    textAlign: 'left',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    color: '#374151',
  },
  navBtnActive: {
    width: '100%',
    padding: '10px 14px',
    background: '#2563eb',
    border: 'none',
    borderRadius: '8px',
    textAlign: 'left',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '700',
    color: 'white',
  },
  content: { flex: 1, minWidth: 0 },
  card: {
    background: 'white',
    borderRadius: '12px',
    padding: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    marginBottom: '16px',
  },
  cardTitle: {
    fontSize: '16px',
    fontWeight: 'bold',
    marginBottom: '16px',
    color: '#111827',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  kpi: {
    borderRadius: '12px',
    padding: '20px',
    color: 'white',
    textAlign: 'center',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: '8px',
    fontSize: '14px',
    boxSizing: 'border-box',
    outline: 'none',
  },
  label: {
    display: 'block',
    fontSize: '13px',
    fontWeight: '600',
    color: '#374151',
    marginBottom: '6px',
  },
  btnPrimary: {
    padding: '10px 20px',
    background: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
  },
  btnLogout: {
    padding: '8px 16px',
    background: 'rgba(255,255,255,0.2)',
    color: 'white',
    border: '1px solid rgba(255,255,255,0.4)',
    borderRadius: '8px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
  },
  badgeOk: {
    background: '#d1fae5',
    color: '#065f46',
    padding: '4px 10px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '700',
  },
  badgeWarn: {
    background: '#fef3c7',
    color: '#92400e',
    padding: '4px 10px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '700',
  },
  badgeErr: {
    background: '#fee2e2',
    color: '#991b1b',
    padding: '4px 10px',
    borderRadius: '8px',
    fontSize: '12px',
    fontWeight: '700',
  },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '16px' },
  th: {
    textAlign: 'left',
    padding: '12px',
    background: '#f3f4f6',
    borderBottom: '1px solid #e5e7eb',
  },
  td: { padding: '10px 12px', borderBottom: '1px solid #e5e7eb' },
};
