export const styles = {
  container: {
    minHeight: '100vh',
    background: '#f1f5f9',
    fontFamily: "'Segoe UI', sans-serif",
  },
  header: {
    background: 'linear-gradient(135deg, #1e3a5f 0%, #dc2626 100%)',
    color: 'white',
    padding: '12px 24px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.2)',
  },
  headerContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    flexWrap: 'wrap',
  },
  logo: { fontSize: '40px' },
  title: { fontSize: '20px', fontWeight: 'bold', margin: 0 },
  subtitle: { fontSize: '13px', opacity: 0.85, margin: 0 },
  main: {
    padding: '20px',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  nav: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    justifyContent: 'center', // centrado
    marginBottom: '20px',
    padding: '0 8px',
  },
  navBtn: {
    padding: '8px 20px',
    background: 'white',
    border: '1px solid #cbd5e1',
    borderRadius: '40px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '500',
    color: '#1e293b',
    transition: 'all 0.2s',
  },
  navBtnActive: {
    padding: '8px 20px',
    background: '#2563eb',
    border: 'none',
    borderRadius: '40px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '700',
    color: 'white',
  },
  content: { flex: 1 },
  card: {
    background: 'white',
    borderRadius: '20px',
    padding: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.1)',
    marginBottom: '16px',
    border: '1px solid #e2e8f0',
  },
  cardTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '16px',
    color: '#1e293b',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1e293b',
    marginBottom: '20px',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  kpi: {
    borderRadius: '20px',
    padding: '20px',
    color: 'white',
    textAlign: 'center',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  formGroup: {
    marginBottom: '16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  labelField: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#334155',
    marginBottom: '0',
  },
  inputField: {
    padding: '10px 14px',
    borderRadius: '40px',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    color: '#1e293b',
    fontSize: '14px',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  selectField: {
    padding: '10px 14px',
    borderRadius: '40px',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    color: '#1e293b',
    fontSize: '14px',
    outline: 'none',
    cursor: 'pointer',
    width: '100%',
    boxSizing: 'border-box',
  },
  textareaField: {
    padding: '10px 14px',
    borderRadius: '20px',
    border: '1px solid #cbd5e1',
    background: '#ffffff',
    color: '#1e293b',
    fontSize: '14px',
    outline: 'none',
    resize: 'vertical',
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
  },
  btnPrimary: {
    padding: '10px 20px',
    background: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '40px',
    fontWeight: '600',
    cursor: 'pointer',
    fontSize: '14px',
    transition: 'all 0.2s',
  },
  btnSecondary: {
    padding: '8px 16px',
    background: '#f1f5f9',
    color: '#1e293b',
    border: '1px solid #cbd5e1',
    borderRadius: '40px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '13px',
  },
  btnLogout: {
    padding: '8px 20px',
    background: 'rgba(255,255,255,0.2)',
    color: 'white',
    border: '1px solid rgba(255,255,255,0.4)',
    borderRadius: '40px',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '600',
  },
  badgeOk: {
    background: '#d1fae5',
    color: '#065f46',
    padding: '4px 12px',
    borderRadius: '40px',
    fontSize: '12px',
    fontWeight: '700',
  },
  badgeWarn: {
    background: '#fef3c7',
    color: '#92400e',
    padding: '4px 12px',
    borderRadius: '40px',
    fontSize: '12px',
    fontWeight: '700',
  },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '16px' },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0,0,0,0.6)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modalContent: {
    background: '#ffffff',
    borderRadius: '24px',
    padding: '28px',
    width: '100%',
    maxWidth: '500px',
    boxShadow: '0 20px 25px -5px rgba(0,0,0,0.1)',
  },
};
